Homework1
LeonidLodygin/ImageProcessing pull request #1
Opened 2023-03-01 13:53 UTC by LeonidLodygin

### First homework. 
Implemented:
1) Rotate the image 90 degrees.
2) 3 new filters for images
3) Processing of an image array
4) Ability to work with console commands
5) Tests
6) Removed code that is not currently used

2023-03-02 10:25 UTC, gsvgit requested changes

2023-03-02 10:25 UTC, gsvgit commented on src/ImageProcessing/Arguments.fs
> +    | [<First; AltCommandLine("-ft")>] Filter of inputPath: string * outputPath: string * filter: Kernel
А что если я хочу применить последовательно несколько трансформаций?
И не надо делать тройки. Сделайте нормальные ключи для всех агрументов.

2023-03-02 10:25 UTC, gsvgit commented on src/ImageProcessing/Arguments.fs
> +                "Apply filter on image or the image directory. Required parameters: input path, output path and filter(Gauss5x5, Gauss7x7, Sharpen, Edges, Emboss)."
Кажется, если всё сделать аккуратно, то Argu сам сгененрирует доступные варианты значений.

2023-03-02 10:25 UTC, gsvgit commented on src/ImageProcessing/CpuImageProcessing.fs
> +let rotate90Degrees (side: string) (image: byte[,]) =
А можно не строку, а кого-то с ровно двумя нормальными значениями?

2023-03-02 10:25 UTC, gsvgit commented on src/ImageProcessing/ImageArrayProcessing.fs
> +        Array.filter (fun (x: string) -> Array.contains (x.Substring(x.LastIndexOf('.'))) Extensions) files
У файла есть методы для номрального получения расширения.

2023-03-03 05:34 UTC, gsvgit commented on build/build.fs
> +        //==> "FsharpLint"
А чего линтер отрубили?

2023-03-03 05:34 UTC, gsvgit commented on src/ImageProcessing/CpuImageProcessing.fs
> +/// Rotating the picture 90 degrees. True - clockwise, false - counterclockwise.
А можно было бы сочинить нормальный тип, а не писать комментрии, которые никто не читает.

2023-03-03 05:34 UTC, gsvgit commented on src/ImageProcessing/CpuImageProcessing.fs
> +                res[i, height - 1 - j] <- image[j, i]
А нельзя ли сделать так, чобы дублирования было чуть меньше?

2023-03-03 05:34 UTC, gsvgit commented on src/ImageProcessing/ImageArrayProcessing.fs
> +let listAllFiles dir =
А почему у Вас снова кто-то с заглавной буквы. а кто-то нет?

2023-03-03 05:34 UTC, gsvgit commented on src/ImageProcessing/Main.fs
> +            printfn $"Zero modifications expected"
Что?

2023-03-03 05:34 UTC, gsvgit commented on src/ImageProcessing/Main.fs
> +            let composition = List.fold (>>) listOfFunc.Head listOfFunc.Tail
Это правда не `reduce`?

2023-03-03 05:47 UTC, LeonidLodygin commented on build/build.fs
> +        //==> "FsharpLint"
С линтером не билдится проект на гитхабе, я оставил 1 запуск билда с проблемой, там ошибка MSB3026. Видимо, из за того, что линтер проверяет файл, другие файлики не могут получить доступ к нему. А так как линтер в этой домашке необязателен, я не стал возиться с этой проблемой

2023-03-03 06:08 UTC, LeonidLodygin commented on src/ImageProcessing/Main.fs
> +            printfn $"Zero modifications expected"
Проверяю, есть ли в строке аргумент модификации, если нет, то и пишу, что их нет....Проблема в моем ломаном английском?...

2023-03-03 06:11 UTC, gsvgit commented on src/ImageProcessing/Main.fs
> +            printfn $"Zero modifications expected"
Ну, либо в Вашем английском, либо в моём понимании происходящего. У Вас тут что-то в духе "Если аргументов нет, то напиши, что их и не ожидалось вообще." Кэп, ты с нами?

2023-03-03 06:11 UTC, gsvgit commented on build/build.fs
> +        //==> "FsharpLint"
Чот странно звучит, если честно.

2023-03-03 06:17 UTC, LeonidLodygin commented on build/build.fs
> +        //==> "FsharpLint"
![image](https://user-images.githubusercontent.com/113135383/222645887-9dcc72dd-addc-4aa7-a2bc-cbf2eb7e1956.png)

2023-03-03 06:22 UTC, gsvgit commented on build/build.fs
> +        //==> "FsharpLint"
Не, я верю и вижу, что сервак падает. Не понятно, почему локально тогда у Вас проходит. Да и сама проблема загадочная.

2023-03-04 10:49 UTC, gsvgit commented on src/ImageProcessing/Arguments.fs
> +    | [<Mandatory; AltCommandLine("-ip")>] InputPath of inputPath: string
Классика: `-i` и `-o`.

2023-03-04 10:49 UTC, gsvgit commented on src/ImageProcessing/CpuImageProcessing.fs
> +    let x = if side = Right then 1 else 0
Что-то такое я уже видел.. А можно как-то без првращение DU в int?

2023-03-04 10:49 UTC, gsvgit commented on src/ImageProcessing/Main.fs
> +            let composition = List.reduce (>>) listOfFunc
А что если тут будет пустой список?

2023-03-04 10:52 UTC, LeonidLodygin commented on src/ImageProcessing/Main.fs
> +            let composition = List.reduce (>>) listOfFunc
![image](https://user-images.githubusercontent.com/113135383/222895858-66eec9f4-9c56-4adb-b7f7-67fa2053ff9f.png)

2023-03-04 10:57 UTC, gsvgit commented on src/ImageProcessing/Main.fs
> +            let composition = List.reduce (>>) listOfFunc
Угу. А кто его обрабатывать нормально будет?

2023-03-06 08:07 UTC, gsvgit approved these changes

2023-03-15 19:22 UTC, merged