Homework3
LeonidLodygin/ImageProcessing pull request #3
Opened 2023-05-14 12:04 UTC by LeonidLodygin

### Third homework.

Implemented:

1. Added kernels for GPU image processing
2. Added agent for logging performed actions
3. Added some tests for GPU processing
4. Code has been restructured

2023-05-15 13:30 UTC, gsvgit requested changes

2023-05-15 13:30 UTC, gsvgit commented on src/ImageProcessing/Agents.fs
> +            })
А не потеряете ли Вы так "хвост" лога, если вдруг всё завершится?

2023-05-15 13:30 UTC, gsvgit commented on src/ImageProcessing/GpuKernels.fs
> +                    let p = r.GlobalID0
А можно ли объединить в одно ядро?

2023-05-15 13:30 UTC, gsvgit commented on src/ImageProcessing/GpuKernels.fs
> +                    let p = r.GlobalID0
А это можно объединить?

2023-05-15 13:30 UTC, gsvgit commented on src/ImageProcessing/GpuProcessing.fs
> +    let kernel = fishEyeKernel clContext localWorkSize
Смотрите, что получается. У Вас каждый фильтр на своей очереди живёт. Между ними синхронизации нет. Как гарантировать, что фильтры в правильном прядке применятся?

2023-05-15 13:30 UTC, gsvgit commented on src/ImageProcessing/Main.fs
> +                            (fun n ->
Куча одинаковых функций.

2023-05-15 22:03 UTC, LeonidLodygin commented on src/ImageProcessing/GpuProcessing.fs
> +    let kernel = fishEyeKernel clContext localWorkSize
Немного не понял сути вопроса, у меня фильтры живут в композиции. Агент принимает композицию фильтров в правильном порядке и саму картинку. Далее, на картинку применяются все фильтры в правильном порядке, а затем картинка сохраняется. Затем, агент берет следующую картинку и т .д.

2023-05-15 22:11 UTC, LeonidLodygin commented on src/ImageProcessing/Agents.fs
> +            })
Если мы говорим про обычных агентов, то там imgProcessor ждет все сообщения от imgSaverа, затем отсылает сообщение логгеру о своем завершении, так что вроде ничего не теряем. Если говорим про суперагентов, то там в функции superImageProcessing мы дожидаемся от каждого суперагента ответа на наше сообщение о завершении работы, так что там тоже все сообщения должны быть записаны.

2023-05-16 08:44 UTC, gsvgit commented on src/ImageProcessing/Agents.fs
> +            })
Угу. Отсылает. Но не жёдт ответа о том, что сообщенеи записано.

2023-05-16 08:45 UTC, gsvgit commented on src/ImageProcessing/GpuProcessing.fs
> +    let kernel = fishEyeKernel clContext localWorkSize
Ага. Только каждый фильтр независимо выполняется на своей очереди, которые асинхронны.

2023-05-16 09:06 UTC, LeonidLodygin commented on src/ImageProcessing/Agents.fs
> +            })
Ааааа, да, я понял, точно.

2023-05-16 09:12 UTC, LeonidLodygin commented on src/ImageProcessing/GpuProcessing.fs
> +    let kernel = fishEyeKernel clContext localWorkSize
Вы меня запутали, у меня же картинки живут на асинхронных потоках, а не фильтры....

2023-05-16 10:02 UTC, LeonidLodygin commented
msgLogger переделан, ожидаю Вашей проверки реквеста, чтобы внести изменения.

2023-05-19 05:40 UTC, gsvgit reviewed
Так понимаю, осталось с очередями разобраться.

2023-05-19 06:39 UTC, gsvgit commented on src/ImageProcessing/Agents.fs
> +                | Msg.SaverEOS ch ->
А зачем Вы сделали десять разных EOS ?

2023-05-19 06:39 UTC, gsvgit commented on tests/ImageProcessing.Tests/GpuTests.fs
> +                  | MirrorHorizontal -> skiptest |> ignore
Скипай всех!

2023-05-19 06:39 UTC, gsvgit commented on src/ImageProcessing/GpuProcessing.fs
> +let mirror side (clContext: ClContext) localWorkSize (queue: MailboxProcessor<Msg>) =
Надо смотреть, как Вы это всё дело вызываете. Может оказаться так, что у Вас каждый раз ядро заново компилируется.

2023-05-19 07:02 UTC, LeonidLodygin commented on src/ImageProcessing/Agents.fs
> +                | Msg.SaverEOS ch ->
Для удобства, чтобы понимать, кто заканчивает работу.

2023-05-19 07:03 UTC, LeonidLodygin commented on tests/ImageProcessing.Tests/GpuTests.fs
> +                  | MirrorHorizontal -> skiptest |> ignore
Скипаются модификации, для которых это некорректный тест

2023-05-19 20:43 UTC, LeonidLodygin commented on tests/ImageProcessing.Tests/GpuTests.fs
> +                  | MirrorHorizontal -> skiptest |> ignore
Я могу размножить этот 1 тест на несколько одинаковых с нужными фильтрами, чтобы не было скиптестов, но, кажется, текущая реализации приятнее и практичнее.

2023-05-23 05:56 UTC, gsvgit approved these changes
Ну что, тесты тупить перестали в итоге?

2023-05-23 05:56 UTC, gsvgit commented on tests/ImageProcessing.Tests/GpuTests.fs
> +                  | MirrorHorizontal -> skiptest |> ignore
На самом деле я скорее про то, что даже этот скип можно компактнее записать. Если я правильно поянл, что здесь просиходит. ПРосто вопрос ещё в том, что как-то много разных конфигураций скипаются. Что там вообще остаётся?

2023-05-23 05:56 UTC, gsvgit commented on src/ImageProcessing/Arguments.fs
> +let first (x, _, _, _) = x
Обычно, если в кортеже больше двух элементов, надо заводить структурку с нормально именованными полями или что-то такое.

2023-07-11 15:51 UTC, merged